#.env config
.env:
    ignoreIfMalformed: false
    ignoreIfMissing: false

#Local MongoDB config
spring.data.mongodb:
    uri: ${env.MONGODB_URI}
    database: ${env.MONGODB_DATABASE}

#App config
app:
    mailjet:
        apiKey: ${env.MAILJET_API_KEY}
        apiSecret: ${env.MAILJET_API_SECRET}
        apiSender: ${env.MAILJET_API_SENDER}